/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mdlFondoFrame;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Alex
 */
public class Fondos extends javax.swing.JPanel {

    /**
     * Creates new form Fondos
     * @param D
     */
    public Fondos(Dimension D) {
        initComponents();
        setSize(D.width, D.height);
    }
    
    @Override
    public void paintComponent(Graphics g){
        Dimension dimension = getSize();
        
        ImageIcon Fondo = new ImageIcon(new ImageIcon(getClass().getResource("/mdlFondoFrame/fondoUNPRG.jpg")).getImage());
        g.drawImage(Fondo.getImage(), 0, 0, dimension.width, dimension.height, null);
        
        this.setOpaque(false);
        super.paintComponent(g);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
